version: '3.7'
services:
  server:
    image: localhost/localchat2:latest
    build: .
    restart: always
    depends_on:
      - db
    ports:
      - 127.0.0.1:9433:9432
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data:z
    ports:
      - 127.0.0.1:5433:5432

volumes:
  postgres-data:
