
services:
  server:
    environment:
      spring_profiles_active: dev
      KEY_STORE_PKCS_FILE: server-dev.p12
      KEY_STORE_PASSWORD: changeme
      POSTGRES_PASSWORD: secret
      ADMIN_PASSWORD: secret
  db:
    environment:
      POSTGRES_PASSWORD: secret
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localchat.dem
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 6060
    ports:
      - 127.0.0.1:6060:6060
    volumes:
      - pgadmin-data:/var/lib/pgadmin:z

volumes:
  pgadmin-data:

