version: '3.7'
services:
  server:
    image: localchat2
    env_file:
      - server.env
    ports:
      - 9432:9432
    networks:
      - postgres
  db:
    image: postgres:12
    environment:
      env_file:
        - server.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 9433:5432
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres-data:
