version: '3.7'
services:
  server:
    image: localchat2
    ports:
      - 9432:9432
    networks:
      - postgres
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data:z
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  posgres-data:
  pgadmin-data: