version: '3.7'
services:
  server:
    image: localchat2
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - server.env
    ports:
      - 192.168.178.26:9432:9432
    networks:
      - postgres
  db:
    image: postgres:12
    env_file:
      - server.env
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 192.168.178.26:9433:5432
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/24

volumes:
  postgres-data:
