version: '3.7'
services:
  server:
    image: localhost/localchat2:latest
    build: .
    restart: always
    depends_on:
      - db
  db:
    image: postgres:15.3-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data:z

volumes:
  postgres-data:
