version: '3.7'
services:
  server:
    image: localhost/localchat2:latest
    restart: always
    depends_on:
      - db
    ports:
      - 9432:9432
  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data:z
    ports:
      - 5432:5432

volumes:
  postgres-data:
