
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  security:
    user:
      name: user
      password: user
      roles: manager

encrypt:
  key-store:
    location: classpath:/server-dev.jks
    password: 'ENC(cFQcCCMyKtaZi3lzoaeefKz7HXcBsI06P5u16nAJlyQFxdRhST2NptADeLRa9a+GX28joWA0duRd7J4/4HFXkVToltybHQq2NrGBaHA1N3o=)'
    alias: localchattest