
spring:
  datasource:
    url: jdbc:postgresql://192.168.178.26:5432/postgres?currentSchema=localchat
    username: hims
    password: 'ENC(fyzyNb35NfO7iXywvA6Z2+WszE9uYY1vVKGJcKMCnsHHY9zjXpuQfnC3R1g6pl710QMzOLk6U3FNVXOuqZBNmg==)'
    driver-class-name: org.postgresql.Driver
  spring:
    flyway:
      url: jdbc:postgresql://192.168.178.26:5432/postgres?currentSchema=localchat
      user: hims
      password: 'ENC(fyzyNb35NfO7iXywvA6Z2+WszE9uYY1vVKGJcKMCnsHHY9zjXpuQfnC3R1g6pl710QMzOLk6U3FNVXOuqZBNmg==)'
      schemas: localchat
      locations: classpath:db/migration
      enabled: true


devtools:
  add-properties: false

key-store:
  location: classpath:/server.jks
  password: ''
  alias: localchat

manage:
  admin:
    password: changeme
