
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN