
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.postgresql.Driver

  spring:
    flyway:
      schemas: public

  security:
    user:
      name: admin
      password: admin
      roles: ADMIN