spring:
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    user: admin
    password: secret
    schemas: public
    locations: classpath:db/migration
    enabled: true

server:
  port: 9432

autoconfigure:
  exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

jasypt.encryptor:
  iv-generator-classname: org.jasypt.iv.RandomIvGenerator
  algorithm: PBEWITHHMACSHA256ANDAES_128

