

devtools:
  add-properties: false

encrypt:
  key-store:
    location: classpath:/server-prod.jks
    password: 'ENC()'
    alias: localchat

server:
  ssl:
    key-store: classpath:server-prod.jks
    key-store-password: 'ENC()'
    key-store-type: jks
    key-alias: localchat
    key-password: 'ENC()'

manage:
  admin:
    password: 'ENC()'
