
server:
  port: 9432

autoconfigure:
  exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration

jasypt.encryptor:
  iv-generator-classname: org.jasypt.iv.RandomIvGenerator
  algorithm: PBEWITHHMACSHA256ANDAES_128
