version: '3.7'
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data:z
    ports:
      - 5432:5432
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:4.24
    restart: unless-stopped
    user: root
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@home
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin:z
    networks:
      - postgres

networks:
  postgres:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"

volumes:
  postgres-data:
  pgadmin-data:
