/**
 * Local Chat API
 * -
 *
 * The version of the OpenAPI document: 0.1
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ConversationMessageDto } from './conversationMessageDto';


export interface ConversationMessagePageDto { 
    convId: number;
    last: boolean;
    messages: Array<ConversationMessageDto>;
    newerThan?: number;
    olderThan?: number;
    page: number;
    pageSize: number;
    regex?: boolean;
    search?: string;
}

