/**
 * Local Chat API
 * -
 *
 * The version of the OpenAPI document: 0.1
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MemberDto } from './memberDto';
import { ConversationNameDto } from './conversationNameDto';


export interface MarkReadResponse { 
    conversation: ConversationNameDto;
    member: MemberDto;
}

