/**
 * Local Chat API
 * -
 *
 * The version of the OpenAPI document: 0.1
 * Contact: admin@localhost
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PermissionDtoRes { 
    administrate: boolean;
    moderate: boolean;
    read: boolean;
    voice: boolean;
    write: boolean;
}

